name: tutorials
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - nb_conda_kernels
  - pip
  - pip:
      - pandas
      - numpy
      - netCDF4
      - cartopy
      - xarray
      - dask
#      - jupyter_contrib_nbextensions
      - cdsapi
      - black[jupyter]
