name: tutorials
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anyio=3.6.2
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attrs=22.2.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.2
  - bleach=6.0.0
  - bokeh=2.4.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cartopy=0.21.1
  - certifi=2022.12.7
  - cffi=1.15.1
  - cftime=1.6.2
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cloudpickle=2.2.1
  - comm=0.1.2
  - contourpy=1.0.7
  - cryptography=39.0.0
  - curl=7.87.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2023.1.1
  - dask-core=2023.1.1
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2023.1.1
  - entrypoints=0.4
  - executing=1.2.0
  - flit-core=3.8.0
  - fonttools=4.38.0
  - freetype=2.12.1
  - fsspec=2023.1.0
  - geos=3.11.1
  - hdf4=4.2.15
  - hdf5=1.12.2
  - heapdict=1.0.1
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.10.2
  - ipykernel=6.21.1
  - ipython=8.9.0
  - ipython_genutils=0.2.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.17.3
  - jupyter_client=8.0.2
  - jupyter_contrib_core=0.4.0
  - jupyter_contrib_nbextensions=0.7.0
  - jupyter_core=5.2.0
  - jupyter_events=0.6.3
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.6.1
  - jupyter_server=2.2.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=3.5.0
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.19.0
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzip=1.9.2
  - libzlib=1.2.13
  - locket=1.0.0
  - lxml=4.9.2
  - lz4=4.2.0
  - lz4-c=1.9.4
  - markupsafe=2.1.2
  - matplotlib-base=3.6.3
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - msgpack-python=1.0.4
  - munkres=1.1.4
  - nb_conda_kernels=2.3.1
  - nbclassic=0.5.1
  - nbclient=0.7.2
  - nbconvert=7.2.9
  - nbconvert-core=7.2.9
  - nbconvert-pandoc=7.2.9
  - nbformat=5.7.3
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - netcdf4=1.6.2
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - numpy=1.24.2
  - openjpeg=2.5.0
  - openssl=3.0.7
  - packaging=23.0
  - pandas=1.5.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.3.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.6.2
  - pooch=1.6.0
  - proj=9.1.1
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.14.0
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyproj=3.4.1
  - pyrsistent=0.19.3
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.4
  - python_abi=3.8
  - pytz=2022.7.1
  - pyyaml=6.0
  - pyzmq=25.0.0
  - readline=8.1.2
  - requests=2.28.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scipy=1.10.0
  - send2trash=1.8.0
  - setuptools=67.1.0
  - shapely=2.0.1
  - six=1.16.0
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.6.2
  - tblib=1.7.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.2
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - unicodedata2=15.0.0
  - urllib3=1.26.14
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.38.4
  - xarray=2023.1.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.12.1
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - black==23.1.0
      - ipywidgets==8.0.4
      - jupyterlab-widgets==3.0.5
      - tokenize-rt==5.0.0
      - tqdm==4.64.1
      - widgetsnbextension==4.0.5
