name: tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - pandas
  - numpy
  - netCDF4
  - xarray
  - scipy
  - dask
  - cartopy
  - pip
  - pip:
    - cdsapi
    - ipywidgets
    - black[jupyter] 
