name: tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyterlab
  - pandas
  - numpy
  - netCDF4
  - xarray
  - dask
  - cartopy
  - jupyter_contrib_nbextensions
  - nb_conda_kernels
  - pip
  - pip:
    - cdsapi
    - black[jupyter] 
